[package]
name = "spl-transfer-hook-interface"
version = "0.6.4"
description = "Solana Program Library Transfer Hook Interface"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/solana-program/transfer-hook"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = { git = "https://github.com/hamkj7hpo/solana.git", rev = "5208a7870826307290c30b7d80768f40267433a1" }
spl-discriminator = "0.4.1"
spl-pod = { git = "https://github.com/hamkj7hpo/spl-pod.git", rev = "0ff7d641b198149f6e0b1265e85b7258db87e254" }
spl-program-error = "0.4.2"
bytemuck = { version = "1.17.1", features = ["derive"] }
