[workspace]
resolver = "2"
members = [
  "clients/cli",
  "interface",
  "program",
]

[package]
name = "spl-transfer-hook-interface"
version = "0.6.4"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/solana-program/transfer-hook"
homepage = "https://solana-program.com"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
path = "interface/src/lib.rs"

[dependencies]
solana-program = { git = "https://github.com/solana-labs/solana.git", rev = "b1e378009ffee4c75965723d3317fccbebcf2524" }
spl-discriminator = "0.4.1"
spl-pod = { git = "https://github.com/hamkj7hpo/spl-pod.git", rev = "0ff7d641b198149f6e0b1265e85b7258db87e254" }
spl-program-error = "0.4.2"
bytemuck = { version = "1.17.1", features = ["derive"] }
